# Generated by Django 6.0.2 on 2026-03-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
